// FORM
export const GET_FORMS = 'GET_FORMS';
export const ADD_FORM = 'ADD_FORM';
export const DELETE_FORM = 'DELETE_FORM';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
// export const UPDATE_FORM = 'UPDATE_FORM';
export const FORM_ERROR = 'FORM_ERROR';

// AUTH
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// REGISTRATIONS
export const GET_REGISTRATIONS = 'GET_REGISTRATIONS';
export const ADD_REGISTRATION = 'ADD_REGISTRATION';
export const DELETE_REGISTRATION = 'DELETE_REGISTRATION';
export const SET_CURRENT_REG = 'SET_CURRENT_REG';
export const CLEAR_CURRENT_REG = 'CLEAR_CURRENT_REG';
// export const UPDATE_REGISTRATION = 'UPDATE_REGISTRATION';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
